# Generated by Django 4.2.23 on 2025-07-15 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('type', models.CharField(choices=[('sidebar', 'Sidebar'), ('main', 'Main')], max_length=255, verbose_name='Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Subscribe Page Content',
                'verbose_name_plural': 'Subscribe Page Contents',
                'db_table': 'subscribe_page_content',
                'ordering': ['-created_at'],
            },
        ),
    ]
