# Generated by Django 4.2.23 on 2025-07-15 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('volume', models.CharField(max_length=50)),
                ('issue_number', models.CharField(max_length=50)),
                ('publication_date', models.DateField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='issue_covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Journal Issue',
                'verbose_name_plural': 'Journal Issues',
                'db_table': 'issue',
                'ordering': ['-publication_date'],
            },
        ),
        migrations.CreateModel(
            name='JournalIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('volume', models.CharField(max_length=50)),
                ('issue_number', models.CharField(max_length=50)),
                ('accessability', models.CharField(choices=[('open_access', 'Open Access'), ('subscription', 'Subscription'), ('restricted', 'Restricted')], default='open_access', max_length=50)),
                ('authors', models.CharField(max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to='journal_issues/')),
                ('publication_date', models.DateField()),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_issues', to='issue.issue')),
            ],
            options={
                'verbose_name': 'Journal Issue Metadata',
                'verbose_name_plural': 'Journal Issue Metadata',
                'db_table': 'journal_issue',
            },
        ),
    ]
