# Generated by Django 4.2.23 on 2025-09-14 09:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0002_issue_description_en_issue_description_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalissue',
            name='citation_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='journalissue',
            name='google_scholar_query',
            field=models.CharField(blank=True, help_text='Custom search query override; defaults to title + authors', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='journalissue',
            name='last_scholar_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalissue',
            name='scholar_cluster_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='description_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='description_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='description_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journalissue',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journalissue',
            name='description_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journalissue',
            name='description_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journalissue',
            name='description_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
