# Generated by Django 4.2.23 on 2025-09-30 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0003_journalissue_citation_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalissue',
            options={},
        ),
        migrations.AlterModelTable(
            name='journalissue',
            table=None,
        ),
    ]
