# Generated by Django 4.2.23 on 2026-07-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0004_alter_journalissue_options_alter_journalissue_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalissue',
            name='doi',
            field=models.CharField(blank=True, help_text='Crossref DOI, e.g. 10.65432/comp.2026.001. Leave blank until registered.', max_length=100, null=True, unique=True),
        ),
    ]
