# Generated by Django 4.2.23 on 2026-07-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0005_journalissue_doi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalissue',
            name='doi',
            field=models.CharField(blank=True, help_text='Crossref DOI, e.g. 10.64964/comp.2026.001. Leave blank until registered.', max_length=100, null=True, unique=True),
        ),
    ]
