# Generated by Django 4.2.23 on 2025-07-15 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Default',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
            ],
            options={
                'verbose_name': 'Default Setting',
                'verbose_name_plural': 'Default Settings',
                'db_table': 'default',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Joining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('institution', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Joining Request',
                'verbose_name_plural': 'Joining Requests',
                'db_table': 'joining',
                'ordering': ['-id'],
            },
        ),
    ]
