# Generated by Django 4.2.23 on 2025-07-15 15:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='default',
            name='value',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
