# Generated by Django 4.2.23 on 2026-07-25 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('issue', '0006_alter_journalissue_doi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(help_text='doi_batch_id sent to Crossref; also the key used to poll for results.', max_length=100, unique=True)),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox (test.crossref.org)'), ('production', 'Production (doi.crossref.org)')], default='sandbox', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('submitted', 'Submitted to Crossref'), ('registered', 'Registered'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('xml', models.TextField(help_text='Exact deposit XML that will be sent to Crossref.')),
                ('log', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_doi_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DOI deposit batch',
                'verbose_name_plural': 'DOI deposit batches',
                'db_table': 'crossref_deposit_batch',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DepositItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_doi', models.CharField(max_length=100)),
                ('resource_url', models.URLField(help_text='Landing page Crossref will resolve the DOI to. Must be publicly reachable.', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('deposited', 'Sent to Crossref'), ('registered', 'Registered'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doi_deposits', to='issue.journalissue')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crossref.depositbatch')),
            ],
            options={
                'verbose_name': 'DOI deposit item',
                'verbose_name_plural': 'DOI deposit items',
                'db_table': 'crossref_deposit_item',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='deposititem',
            constraint=models.UniqueConstraint(fields=('batch', 'article'), name='unique_article_per_batch'),
        ),
    ]
