# Generated by Django 4.2.23 on 2025-07-15 15:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
